Feature/tour page
attech-org/air pull request #10
Opened 2021-11-04 16:16 UTC by fominmaksim

Completed header

2021-11-04 16:27 UTC, AndrewKaenko approved these changes
Good job. No errors found

2021-11-05 09:27 UTC, alexandrtovmach requested changes
again you forgot to remove mocks =) _src/MOCK.jsx_

2021-11-05 09:40 UTC, alexandrtovmach requested changes

2021-11-05 09:40 UTC, alexandrtovmach commented on package.json
> +    "react-date-picker": "^8.3.5",
not used ― should be removed

2021-11-05 09:40 UTC, alexandrtovmach commented on package.json
> +    "react-transition-group": "^4.4.2",
not used ― should be removed

2021-11-05 10:00 UTC, alexandrtovmach approved these changes

2021-11-05 10:00 UTC, merged