Feature/search
attech-org/air pull request #8
Opened 2021-11-02 16:06 UTC by fominmaksim

https://trello.com/c/YiknL5oU - completed the task

2021-11-02 16:59 UTC, AndrewKaenko approved these changes
Everything is checked. No questions

2021-11-02 17:51 UTC, alexandrtovmach requested changes
- _src/MOCK.jsx_ - should be deleted
- if no date range provided, show all results based on cities only

2021-11-02 17:51 UTC, alexandrtovmach commented on src/containers/SearchPanel.jsx
> +  text-decoration: none;
useless

2021-11-02 17:51 UTC, alexandrtovmach commented on src/containers/SearchPanel.jsx
> +      </StyledLink>
```
<StyledLink
        to={`/search-result?departureCity=${departureCityInput}&arrivalCity=${arrivalCityInput}&departureStartDate=${departureStartDateInput}&departureEndDate=${departureEndDateInput}`}
      >
          <NextBtn>
            <Arrow>&#8594;</Arrow>
          </NextBtn>
          <StyledP>Next</StyledP>
      </StyledLink>
```

`<ButtonSection>` - useless. Move all styles from it to parent Styled link and remove it from layout

2021-11-02 17:51 UTC, alexandrtovmach commented on src/containers/SearchResult.jsx
> +          <FlightDurationP>{flightDuration().toString()}</FlightDurationP>
```suggestion
          <FlightDurationP>{flightDuration()}</FlightDurationP>
```

2021-11-02 17:51 UTC, alexandrtovmach commented on src/pages/Search.jsx
> +// import { BrowserRouter as Router, Switch, Route } from "react-router-dom"
remove comments

2021-11-02 17:51 UTC, alexandrtovmach commented on src/pages/Search.jsx
> +// import SearchResult from "./SearchResult"
remove comments

2021-11-02 17:51 UTC, alexandrtovmach commented on src/pages/SearchResult.jsx
> +                new Date(departureDate) >= new Date(departureStartDateInput) &&
```suggestion
                (!departureStartDateInput || new Date(departureDate) >= new Date(departureStartDateInput)) &&
```

2021-11-02 17:51 UTC, alexandrtovmach commented on src/pages/SearchResult.jsx
> +                new Date(departureDate) <= new Date(departureEndDateInput)
```suggestion
                (!departureEndDateInput || new Date(departureDate) <= new Date(departureEndDateInput))
```

2021-11-03 10:35 UTC, alexandrtovmach approved these changes

2021-11-03 11:56 UTC, merged